// Copyright 2021 - 2022 @skyekiwi/crust-network authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @skyekiwi/dev, do not edit

export const packageInfo = { name: '@skyekiwi/crust-network', version: '0.5.2-10' };
