// Copyright 2021 @skyekiwi/util authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @skyekiwi/dev, do not edit

export const packageInfo = { name: '@skyekiwi/util', version: '0.8.4-1' };
