// Copyright 2021 @skyekiwi/file authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @skyekiwi/dev, do not edit

export const packageInfo = { name: '@skyekiwi/file', version: '1.0.1' };
