// Copyright 2021 @skyekiwi/secret-registry authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @skyekiwi/dev, do not edit

export const packageInfo = { name: '@skyekiwi/secret-registry', version: '0.7.7-0' };
