// Copyright 2021 @skyekiwi/ipfs authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @skyekiwi/dev, do not edit

export const packageInfo = { name: '@skyekiwi/ipfs', version: '0.6.2-1' };
