// Copyright 2021 @skyekiwi/wasm-contract authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @skyekiwi/dev, do not edit

export const packageInfo = { name: '@skyekiwi/wasm-contract', version: '0.5.2-10' };
